# Generated by Django 4.1.1 on 2022-10-16 14:21

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_create_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(
                blank=True,
                upload_to="mediafiles/pet-photos/",
                validators=[petstagram.photos.validators.validate_file_lt_5mb],
            ),
        ),
    ]
