# Generated by Django 4.1.2 on 2022-10-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_department_project_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="web.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="projects",
            field=models.ManyToManyField(blank=True, to="web.project"),
        ),
    ]
