# Generated by Django 4.1.2 on 2022-10-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_employee_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="city",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
