# Generated by Django 4.1.2 on 2022-10-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_employee_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("has_private_office", models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
