# Generated by Django 4.1.2 on 2022-10-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="level",
            field=models.CharField(
                choices=[(1, "Supervisor"), (2, "Manager"), (3, "Director")],
                max_length=30,
                null=True,
                verbose_name="Proficiency level",
            ),
        ),
        migrations.AddField(
            model_name="manager",
            name="salary",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="manager",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="manager",
            name="has_private_office",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Private office?"
            ),
        ),
    ]
