# Generated by Django 4.1.2 on 2022-10-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_employee_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("employee", models.ManyToManyField(to="web.employee")),
            ],
        ),
    ]
