# Generated by Django 4.1.2 on 2022-10-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_employee_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="city",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
