# Generated by Django 4.1.2 on 2022-10-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_accesscard"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesscard",
            name="card_type",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
