# Generated by Django 4.1.2 on 2022-10-15 13:40

from django.db import migrations
from django.db.migrations import RunPython
from django.utils.text import slugify


def add_slug(apps, schema_editor):
    department_model = apps.get_model('web', 'Department')
    department_data = department_model.objects.all()

    for department in department_data:
        department.slug = slugify(f'{department.id} {department.name}')

    department_model.objects.bulk_update(department_data, ['slug'])


def delete_slug(apps, schema_editor):
    department_model = apps.get_model('web', 'Department')
    department_data = department_model.objects.all()

    for department in department_data:
        department.slug = None

    department_model.objects.bulk_update(department_data, ['slug'])

class Migration(migrations.Migration):
    dependencies = [
        ("web", "0014_department_slug"),
    ]

    operations = [
        RunPython(add_slug, delete_slug)
    ]
