# Generated by Django 4.1.2 on 2022-10-16 07:30

from django.db import migrations, models
import models_demo.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_alter_department_slug_to_existing_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[models_demo.web.validators.validate_after_today],
            ),
        ),
    ]
