# Generated by Django 4.1.2 on 2022-10-24 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_person_todomodel_assignee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todomodel",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todos",
                to="web.person",
            ),
        ),
    ]
