# Generated by Django 4.1.1 on 2022-10-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("personal_photo", models.URLField()),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
