# Generated by Django 4.1.1 on 2022-10-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_create_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
